// throw new ReferenceError();
try{
    throw new ReferenceError();
}
catch(err){
    // console.log(err)
    console.log("there was a refrence error")
}
console.log("my program does not stop")